services:
  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - API_PORT=3000
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
